[package]

name = "cpython"
version = "0.0.3"
description = "Bindings to Python"
authors = ["Daniel Grunwald <daniel@danielgrunwald.de>"]
readme = "README.md"
keywords = [
    "python",
    "cpython",
    "libpython27",
]
homepage = "https://github.com/dgrunwald/rust-cpython"
repository = "https://github.com/dgrunwald/rust-cpython.git"
documentation = "http://dgrunwald.github.io/rust-cpython/doc/cpython/"
license = "MIT"
exclude = [
    ".gitignore",
    ".travis.yml",
    "appveyor.yml",
    ".cargo/config",
    "python27-sys",
    "python32-sys",
]
build = "build.rs"

[dependencies]
libc = "*"
num = "*"
interpolate_idents = "*"
abort_on_panic = "1.0"

# These features are both optional, but you must pick one to 
# indicate which python ffi you are trying to bind to.
[dependencies.python27-sys]
optional = true
path = "python27-sys"

[dependencies.python3-sys]
optional = true


# Optional features to support explicitly specifying python minor version.
# If you don't care which minor version, just specify python3-sys as a 
# feature.
python-3-5 = ["python3-sys/python-3-5"]
python-3-4 = ["python3-sys/python-3-4"]
